---
title: "p8105_hw1_wz2630"
output: github_document
date: "2023-09-15"
---

Problem 1
```{r}
library(moderndive)
library(tidyverse)

data("early_january_weather")

# the variables in this dataset, including names / values of important variables
skimr::skim(early_january_weather)

# the size of the dataset
nrow(early_january_weather)

ncol(early_january_weather)

#the mean temperature
temp <- pull(early_january_weather, temp)
mean(temp)

#scatterplot

ggplot(early_january_weather, 
       aes(x = time_hour, y = temp)) + 
       geom_point(aes(col = humid)) + 
       labs(y = "Temperature (F)", 
            x = "Time in Hours", 
            title = "Temperature at Different Times in Early January")

# In the early_january_weather, there are 358 observations and 15 variables. 

# There are many missing data in variables wind_gust and pressure. The variable time_hour observations are in year, month, day, and hour; temp and humid variables are in continuous numbers.

# The mean temperature is 39.58 degrees F.

# There is an overall increasing trend in temperature as time progresses in January. Based on the scatterplot, there are outliers of temperatures greater than 50 degrees and below 30 degrees. Majorit of data points are within [30,50] temperatures.


ggsave("scatter_plot.pdf")
```



Problem 2
```{r}
df <- tibble(
  random_sample = rnorm(10),
  vec_logical = random_sample > 0,
  vec_char = c("one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"),
  vec_factor = factor(c("low", "low", "low", "medium", "medium", "medium", 
                        "high", "high", "high","high"))
            )

random_sample <- pull(df, random_sample)
mean(random_sample)

vec_logical <- pull(df, vec_logical)
mean(vec_logical)

# We cannot take the mean of 'vec_char' and 'vec_factor' because these variables are character values.
# We can only take the mean of numerical variables.

```

```{r, eval=FALSE}
vec_logical <- pull(df, vec_logical)
logical_convert <- as.numeric(vec_logical)
mean(logical_convert)

vec_char <- pull(df, vec_char)
char_convert <- as.numeric(vec_char)
mean(char_convert)

vec_factor <- pull(df, vec_factor)
factor_convert <- as.numeric(vec_factor)
mean(factor_convert)
# The as.numeric function is able to convert factor into numeric since it has levels that 
# allows a numerical conversion. However, as.numeric function is not able to convert 
# character values into numeric values.
```

